# -*- coding: utf-8 -*-
"""day3_homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azdG-jTfC7ISuVpS9B1L9RuTx8QH061-
"""

#Day-3 HomeWork Answers : User Login Application 

#Answer 1

yourUsername = "Tuba"   
yourPassword = "12345"

check = False

myusername = input("Please enter your username: ")
mypassword = input("Please enter your password: ")

for x in range(2):

  if myusername == yourUsername and mypassword == yourPassword:
    print("You have successfully logged in!")
    check = True
    break
  
  else:
    print ("Your username or password is incorrect!")
    myusername = input("Please enter your username: ")
    mypassword = input("Please enter your password: ")

if not check:
  print("Your account has been blocked.")

#Extra Answer - with Dictionary Method

d = {"my_username":"Tuba", "my_password":"12345"}
    
check = False

username = input("Please enter your username: ")
password = input("Please enter your password: ")

for x in range(3):

    if username == d["my_username"] and password == d["my_password"]:
        print("You have successfully logged in!")
        check = True
        break

    else: 
      print("Your username or password is incorrect!")
      username = input("Please enter your username: ")
      password = input("Please enter your password: ")

if not check:
  print("Your account has been blocked.")